too much to tell but it works

diff --git a/runcore b/runcore
--- a/runcore
+++ b/runcore
@@ -37,7 +37,7 @@ function cleanroom() {
     echo export CORE_SYSTEM='"'${RUNCORE}/system'"'
 
     # If input was piped, use it with the command, otherwise just run the command
-    echo "$@ $([ -n "$input" ] && echo " < $input")"
+    echo "$@ $([ -n "$input" ] && echo "< $input")"
   } |  env -i bash
 
   # capture return code
@@ -230,14 +230,47 @@ function runcompose() {
 # execute inside docker
 function runexec() {
   local flags=( )
+  local input
+  local error
 
+  # Check for flags but internally we manage -t and -i
   while [[ $# -gt 0 && $1 == -* ]]; do
-    flags+=( "$1" )
+    [[ "$1" != "-t" && "$1" != "-i" && "$1" != "-it" && "$1" != "-ti" ]] && flags+=("$1")
     shift
   done
 
-  isupordie "$1"
-  docker exec "${flags[@]}" "${GITROOT##*/}-$(readlink "${RUNCORE}/.settings" | sed -e 's/^.*\///')-${1}-1" "${@:2}"
+  # make sure tty is handled properly in both directions
+  [[ "$flags" != *"-t"* ]] && [ -t 0 ] && flags+=( -it )
+  [[ "$flags" != *"-i"* ]] && [ ! -t 0 ] && flags+=( -i )
+
+  # check for piped input
+  [ ! -t 0 ] && input=$(mktemp) && cat - > "$input"
+
+  # make sure we have the container up
+  if ! isup "$1"; then
+    die "${RUNNAME^} ${1^} is not running yet...\n\n  $RUNNAME up\n  $RUNNAME up $1"
+    [ -n "$input" ] && rm -f "$input"
+  fi
+
+  # run the command
+  if [ -n "$input" ]; then
+    cat $input | docker exec "${flags[@]}" \
+    "${GITROOT##*/}-$(readlink "${RUNCORE}/.settings" | sed -e 's/^.*\///')-${1}-1" \
+    "${@:2}"
+  else
+    docker exec "${flags[@]}" \
+    "${GITROOT##*/}-$(readlink "${RUNCORE}/.settings" | sed -e 's/^.*\///')-${1}-1" \
+    "${@:2}"
+  fi
+
+  # capture return code
+  error=$?
+
+  # clean up temporary file
+  [ -n "$input" ] && rm -f "$input"
+
+  #return error if we have one
+  return $error
 }
 
 # serve settings
