finally got config working properly! THat was a doozy!

diff --git a/system/pg_scripts/pg_dataload b/system/pg_scripts/pg_dataload
--- a/system/pg_scripts/pg_dataload
+++ b/system/pg_scripts/pg_dataload
@@ -23,8 +23,8 @@ function gen_conflict_clause() {
   " | PGHOST= PGHOSTADDR= psql -v QUIET=1 ON_ERROR_STOP=1 --username "$POSTGRES_USER" --no-password --no-psqlrc --dbname "$POSTGRES_DB" -t -A
 }
 
-# function to generate where clause for rdeletes
-function gen_where_clause() {
+# function to generate where clause for deletes
+function gen_delete_clause() {
   local table="$1"
   local temp_table="$2"
   local headers="$3"
@@ -50,15 +50,15 @@ function gen_where_clause() {
 function load_sql_data() {
   local table="$1"
   local datafile="$2"
-  local headers=$(head -n 1 "$datafile")
+  local headers=$(sed -n '1s/..//p' "$datafile")
   local columns=${headers//:/, }
   local update_columns=$(echo "$columns" | sed 's/[^,]*/\0 = EXCLUDED.&/g')
   local temp_table="temp_data_${table//./_}"
   local conflict_clause="$(gen_conflict_clause "$table" "$update_columns")"
-  local where_clause="$(gen_where_clause "$table" "$temp_table" "$headers")"
+  local delete_clause="$(gen_delete_clause "$table" "$temp_table" "$headers")"
 
   # log that we are starting
-  echo "updating table \"$table\" with new settings..."
+  echo -n "updating table \"$table\" with new settings... "
 
   # execute the SQL commands within a single transaction
   local dataload_sql="
@@ -71,7 +71,7 @@ function load_sql_data() {
     ALTER TABLE $temp_table ADD COLUMN _ char(1);
 
     -- Copy data from the CSV file into the temporary table
-    COPY $temp_table(_, $columns) FROM '$datafile' DELIMITER ':' CSV HEADER;
+    COPY $temp_table(_,$columns) FROM '$datafile' DELIMITER ':' CSV HEADER;
 
     -- Insert data and handle conflicts if any exist
     INSERT INTO $table ($columns)
@@ -82,7 +82,7 @@ function load_sql_data() {
     -- Delete based on matching column values
     DELETE FROM $table
     USING $temp_table
-    WHERE $temp_table._='-' AND $where_clause;
+    WHERE $temp_table._='-' AND $delete_clause;
 
     -- Export updated data back to the datafile file
     COPY (
@@ -98,13 +98,13 @@ function load_sql_data() {
 
   # echo "$conflict_statements"
   # echo "$dataload_sql"
-  echo "$dataload_sql" | PGHOST= PGHOSTADDR= psql -v QUIET=1 ON_ERROR_STOP=1 --username "$POSTGRES_USER" --no-password --no-psqlrc --dbname "$POSTGRES_DB" -t -A
+  local dataload_err=$(echo "$dataload_sql" | PGHOST= PGHOSTADDR= psql -v QUIET=1 ON_ERROR_STOP=1 --username "$POSTGRES_USER" --no-password --no-psqlrc --dbname "$POSTGRES_DB" -t -A 2>&1)
 
   # log return
   local rtn="$?"
 
   # show success message
-  [ "$rtn" = 0 ] && "DATA LOADED." || echo "DATA FAILED."
+  [ "$rtn" = 0 ] && echo "DATA LOADED." || echo -e "\n$dataload_err"
 
   # pass on return
   return $rtn
@@ -116,7 +116,7 @@ function load_datafile() {
   local datafile="/datafiles/$table"
 
   # make sure we have a tempfile
-  [ ! -f "$datafile" ] && echo "datafile not found for table \"$table\"." && return
+  [ ! -f "$datafile" ] && echo "datafile not found for table \"$table\"." >&2 && return
 
   # create tempfile
   local tempfile="$(mktemp "/tmp/datafile_$table.XXXXXX")"
@@ -141,14 +141,17 @@ function load_datafile() {
 }
 
 # if we have a file passed in process that file
-[ -n "$1" ] && load_datafile $1 && exit $?
+if [ -n "$1" ]; then
+  load_datafile "$1"
+
+  exit $?
+fi
 
 # otherwise process tables in the correct order
 for tablename in $(pg_tableorder); do
-  # check if the file exists in the datafiles
   if [ -f "/datafiles/$tablename" ]; then
     # load data from file
-    load_datafile "$tablename" 1>/dev/null 2>&1
+    (load_datafile "$tablename" 1>/dev/null) 2>&1
 
     # aggregate return
     rtn=$((rtn + 1))
